
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import javax.swing.*;
import javax.sql.*;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author alexd
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Connection conn = null;
    public Statement stmt;
    public ResultSet rs;

    public Principal() {
        initComponents();

        abas.setEnabledAt(1, false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtLogin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        txtSigla = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        abas.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel3.setLayout(null);
        jPanel3.add(txtLogin);
        txtLogin.setBounds(30, 40, 200, 30);

        jButton1.setText("Entre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(90, 140, 90, 30);

        jLabel1.setText("Usuário");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 20, 40, 14);

        jLabel2.setText("Senha");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 80, 34, 14);
        jPanel3.add(txtSenha);
        txtSenha.setBounds(30, 100, 200, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(200, 110, 260, 200);

        abas.addTab("Login", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        txtSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSiglaActionPerformed(evt);
            }
        });
        jPanel2.add(txtSigla);
        txtSigla.setBounds(160, 40, 430, 28);
        jPanel2.add(txtNome);
        txtNome.setBounds(160, 80, 430, 31);
        jPanel2.add(txtDesc);
        txtDesc.setBounds(160, 130, 430, 122);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Sigla");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 40, 80, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Nome");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 90, 90, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Descrição");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 130, 100, 17);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        jPanel2.add(btnInserir);
        btnInserir.setBounds(30, 290, 140, 30);

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeletar);
        btnDeletar.setBounds(230, 290, 150, 30);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAtualizar);
        btnAtualizar.setBounds(430, 290, 170, 30);

        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimparCampos);
        btnLimparCampos.setBounds(30, 233, 120, 20);

        btnPrimeiro.setText("<<Primeiro");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrimeiro);
        btnPrimeiro.setBounds(40, 390, 100, 23);

        btnAnterior.setText("< Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel2.add(btnAnterior);
        btnAnterior.setBounds(190, 390, 100, 23);

        btnProximo.setText("Próximo >");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        jPanel2.add(btnProximo);
        btnProximo.setBounds(340, 390, 110, 23);

        btnUltimo.setText("Último >>");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        jPanel2.add(btnUltimo);
        btnUltimo.setBounds(490, 390, 110, 23);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("Navegação Entre Registros");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(180, 340, 290, 40);

        abas.addTab("Cadastro", jPanel2);

        getContentPane().add(abas);
        abas.setBounds(10, 0, 650, 460);

        setBounds(0, 0, 682, 502);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String senha = new String(txtSenha.getPassword());

        if (txtLogin.getText().equals("adm") && senha.equals("123")) {
            abas.setEnabledAt(1, true);
            abas.setSelectedIndex(1);
        } else {

            JOptionPane.showMessageDialog(null,
                    "Dados de Login Incorretos",
                    "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/dbaula4",
                    "root", "123");
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            String sql = "INSERT INTO curso VALUES('"
                    + txtSigla.getText() + "','"
                    + txtNome.getText() + "','"
                    + txtDesc.getText() + "')";
            //JOptionPane.showMessageDialog(null, sql);
            int i = 0;
            i = stmt.executeUpdate(sql);//executando o comando 
            stmt.close();
            if (i > 0) {
                JOptionPane.showMessageDialog(null, "Curso cadastrado com sucesso!");
                //abreTabela();
            }
        } catch (ClassNotFoundException e) {
            System.out.println(e);
        } catch (SQLException e) {
            System.out.println(e);
        } 
    }//GEN-LAST:event_btnInserirActionPerformed

    private void txtSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiglaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiglaActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:  
        
        String query1 = "UPDATE curso SET sigla=";
        String a = txtSigla.getText();
        
        try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/dbaula4", "root", "123");
                stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                ResultSet.CONCUR_UPDATABLE);
                String sql = query1 + "'" + txtSigla.getText() + "',"
                + "nome='" + txtNome.getText() + "',"
                + "descricao='" + txtDesc.getText()
                + "' where sigla=" + "'" + txtSigla.getText() + "'";
               //JOptionPane.showMessageDialog(null, sql);
                int i = 0;
                i = stmt.executeUpdate(sql);//executando o comando sql
                int y = 0;
                stmt.close();
                y = stmt.CLOSE_CURRENT_RESULT;
                if (i > 0) {
                JOptionPane.showMessageDialog(null, "Curso alterado com sucesso!");
                //abreTabela();
                }
            } 
        
        catch (ClassNotFoundException e) {
        System.out.println(e);
        } catch (SQLException e) {
        System.out.println(e);
        }
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        
        String query1 = "DELETE FROM curso WHERE(sigla=";
        String a = txtSigla.getText();
        try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/dbaula4", "root", "123");
                stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                ResultSet.CONCUR_UPDATABLE);
                String sql = query1 + "'" + txtSigla.getText() + "')";
                //JOptionPane.showMessageDialog(null, sql);
                int i = 0;
                i = stmt.executeUpdate(sql);//executando o comando sql
                stmt.close();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, "Curso deletado com sucesso!");
                    // limpando campos
                    txtSigla.setText("");
                    txtNome.setText("");
                    txtDesc.setText("");

                    //abreTabela();
                }
            }   
                catch (ClassNotFoundException e) {
                System.out.println(e);
                } catch (SQLException e) {
                System.out.println(e);
                }
        
        
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        // TODO add your handling code here:
        txtSigla.setText("");
        txtNome.setText("");
        txtDesc.setText("");
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        // TODO add your handling code here:
        try {
            rs.first();
            atualiza_campos();
            } 
            catch (SQLException e) {
            System.out.println(e);
            }

        
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        try {
            rs.previous();
            atualiza_campos();
            } 
            catch (SQLException e) {
            System.out.println(e);
            }
        
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        // TODO add your handling code here:
        try {
            rs.next();
            atualiza_campos();
            } 
            catch (SQLException e) {
            System.out.println(e);
            }
        
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        // TODO add your handling code here:
        try {
            rs.last();
            atualiza_campos();
            } 
            catch (SQLException e) {
            System.out.println(e);
            }
        
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        abreTabela();
    }//GEN-LAST:event_formWindowOpened


    
    /**
     * @param args the command line arguments
     */
    
    public void atualiza_campos(){
        try {
                txtSigla.setText("" + rs.getString("sigla"));
                txtNome.setText("" + rs.getString("Nome"));//
                txtDesc.setText("" + rs.getString("descricao"));
            } 
            catch (SQLException e) {
            System.out.println(e);
            }
    }
    
    public void abreTabela(){
        String query1 = "Select * from curso";
        try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/dbaula4",
                "root", "123");
                stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                ResultSet.CONCUR_READ_ONLY);
                rs = stmt.executeQuery(query1);//executando o comando sql
                rs.first();//estamos movendo o cursor para o primeiro registro pesquisado
                atualiza_campos();
                //conteudo da coluna sigla
                } catch (ClassNotFoundException e) {
                System.out.println(e);
                } catch (SQLException e) {
                System.out.println(e);
        }

    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtSigla;
    // End of variables declaration//GEN-END:variables
}
